/*
lcdn-mapping

LCDN Mapping API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lcdn_mapping

import (
	"encoding/json"
)

// BgpConfig3 BGP config summary read schema.
type BgpConfig3 struct {
	// The unique identifier for a BGP configuration.
	BgpConfigId int32 `json:"bgpConfigId"`
	// A unique name for the entity.
	Name string `json:"name"`
}

// NewBgpConfig3 instantiates a new BgpConfig3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBgpConfig3(bgpConfigId int32, name string) *BgpConfig3 {
	this := BgpConfig3{}
	this.BgpConfigId = bgpConfigId
	this.Name = name
	return &this
}

// NewBgpConfig3WithDefaults instantiates a new BgpConfig3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBgpConfig3WithDefaults() *BgpConfig3 {
	this := BgpConfig3{}
	return &this
}

// GetBgpConfigId returns the BgpConfigId field value
func (o *BgpConfig3) GetBgpConfigId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BgpConfigId
}

// GetBgpConfigIdOk returns a tuple with the BgpConfigId field value
// and a boolean to check if the value has been set.
func (o *BgpConfig3) GetBgpConfigIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BgpConfigId, true
}

// SetBgpConfigId sets field value
func (o *BgpConfig3) SetBgpConfigId(v int32) {
	o.BgpConfigId = v
}

// GetName returns the Name field value
func (o *BgpConfig3) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BgpConfig3) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BgpConfig3) SetName(v string) {
	o.Name = v
}

func (o BgpConfig3) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["bgpConfigId"] = o.BgpConfigId
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableBgpConfig3 struct {
	value *BgpConfig3
	isSet bool
}

func (v NullableBgpConfig3) Get() *BgpConfig3 {
	return v.value
}

func (v *NullableBgpConfig3) Set(val *BgpConfig3) {
	v.value = val
	v.isSet = true
}

func (v NullableBgpConfig3) IsSet() bool {
	return v.isSet
}

func (v *NullableBgpConfig3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBgpConfig3(val *BgpConfig3) *NullableBgpConfig3 {
	return &NullableBgpConfig3{value: val, isSet: true}
}

func (v NullableBgpConfig3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBgpConfig3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


