/*
lcdn-mapping

LCDN Mapping API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lcdn_mapping

import (
	"encoding/json"
)

// GeoipConfigCollection GeoIP config collection.
type GeoipConfigCollection struct {
	BgpConfigs *[]GeoipConfig2 `json:"bgpConfigs,omitempty"`
	Page PageType `json:"page"`
}

// NewGeoipConfigCollection instantiates a new GeoipConfigCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeoipConfigCollection(page PageType) *GeoipConfigCollection {
	this := GeoipConfigCollection{}
	this.Page = page
	return &this
}

// NewGeoipConfigCollectionWithDefaults instantiates a new GeoipConfigCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeoipConfigCollectionWithDefaults() *GeoipConfigCollection {
	this := GeoipConfigCollection{}
	return &this
}

// GetBgpConfigs returns the BgpConfigs field value if set, zero value otherwise.
func (o *GeoipConfigCollection) GetBgpConfigs() []GeoipConfig2 {
	if o == nil || o.BgpConfigs == nil {
		var ret []GeoipConfig2
		return ret
	}
	return *o.BgpConfigs
}

// GetBgpConfigsOk returns a tuple with the BgpConfigs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoipConfigCollection) GetBgpConfigsOk() (*[]GeoipConfig2, bool) {
	if o == nil || o.BgpConfigs == nil {
		return nil, false
	}
	return o.BgpConfigs, true
}

// HasBgpConfigs returns a boolean if a field has been set.
func (o *GeoipConfigCollection) HasBgpConfigs() bool {
	if o != nil && o.BgpConfigs != nil {
		return true
	}

	return false
}

// SetBgpConfigs gets a reference to the given []GeoipConfig2 and assigns it to the BgpConfigs field.
func (o *GeoipConfigCollection) SetBgpConfigs(v []GeoipConfig2) {
	o.BgpConfigs = &v
}

// GetPage returns the Page field value
func (o *GeoipConfigCollection) GetPage() PageType {
	if o == nil {
		var ret PageType
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *GeoipConfigCollection) GetPageOk() (*PageType, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *GeoipConfigCollection) SetPage(v PageType) {
	o.Page = v
}

func (o GeoipConfigCollection) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BgpConfigs != nil {
		toSerialize["bgpConfigs"] = o.BgpConfigs
	}
	if true {
		toSerialize["page"] = o.Page
	}
	return json.Marshal(toSerialize)
}

type NullableGeoipConfigCollection struct {
	value *GeoipConfigCollection
	isSet bool
}

func (v NullableGeoipConfigCollection) Get() *GeoipConfigCollection {
	return v.value
}

func (v *NullableGeoipConfigCollection) Set(val *GeoipConfigCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableGeoipConfigCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableGeoipConfigCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeoipConfigCollection(val *GeoipConfigCollection) *NullableGeoipConfigCollection {
	return &NullableGeoipConfigCollection{value: val, isSet: true}
}

func (v NullableGeoipConfigCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeoipConfigCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


