/*
lcdn-mapping

LCDN Mapping API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lcdn_mapping

import (
	"encoding/json"
)

// SiteMap3 Site Map collection.
type SiteMap3 struct {
	Maps []SiteMap2 `json:"maps"`
	Page PageType `json:"page"`
}

// NewSiteMap3 instantiates a new SiteMap3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteMap3(maps []SiteMap2, page PageType) *SiteMap3 {
	this := SiteMap3{}
	this.Maps = maps
	this.Page = page
	return &this
}

// NewSiteMap3WithDefaults instantiates a new SiteMap3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteMap3WithDefaults() *SiteMap3 {
	this := SiteMap3{}
	return &this
}

// GetMaps returns the Maps field value
func (o *SiteMap3) GetMaps() []SiteMap2 {
	if o == nil {
		var ret []SiteMap2
		return ret
	}

	return o.Maps
}

// GetMapsOk returns a tuple with the Maps field value
// and a boolean to check if the value has been set.
func (o *SiteMap3) GetMapsOk() (*[]SiteMap2, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Maps, true
}

// SetMaps sets field value
func (o *SiteMap3) SetMaps(v []SiteMap2) {
	o.Maps = v
}

// GetPage returns the Page field value
func (o *SiteMap3) GetPage() PageType {
	if o == nil {
		var ret PageType
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *SiteMap3) GetPageOk() (*PageType, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *SiteMap3) SetPage(v PageType) {
	o.Page = v
}

func (o SiteMap3) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["maps"] = o.Maps
	}
	if true {
		toSerialize["page"] = o.Page
	}
	return json.Marshal(toSerialize)
}

type NullableSiteMap3 struct {
	value *SiteMap3
	isSet bool
}

func (v NullableSiteMap3) Get() *SiteMap3 {
	return v.value
}

func (v *NullableSiteMap3) Set(val *SiteMap3) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteMap3) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteMap3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteMap3(val *SiteMap3) *NullableSiteMap3 {
	return &NullableSiteMap3{value: val, isSet: true}
}

func (v NullableSiteMap3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteMap3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


