/*
lcdn-mapping

LCDN Mapping API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lcdn_mapping

import (
	"encoding/json"
)

// GeoipConfig3 GeoIP config create schema.
type GeoipConfig3 struct {
	Type TypeType `json:"type"`
	// A unique name for the entity.
	Name string `json:"name"`
	// A description for the entity.
	Description *string `json:"description,omitempty"`
}

// NewGeoipConfig3 instantiates a new GeoipConfig3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeoipConfig3(type_ TypeType, name string) *GeoipConfig3 {
	this := GeoipConfig3{}
	this.Type = type_
	this.Name = name
	return &this
}

// NewGeoipConfig3WithDefaults instantiates a new GeoipConfig3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeoipConfig3WithDefaults() *GeoipConfig3 {
	this := GeoipConfig3{}
	return &this
}

// GetType returns the Type field value
func (o *GeoipConfig3) GetType() TypeType {
	if o == nil {
		var ret TypeType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GeoipConfig3) GetTypeOk() (*TypeType, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GeoipConfig3) SetType(v TypeType) {
	o.Type = v
}

// GetName returns the Name field value
func (o *GeoipConfig3) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GeoipConfig3) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GeoipConfig3) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GeoipConfig3) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoipConfig3) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GeoipConfig3) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GeoipConfig3) SetDescription(v string) {
	o.Description = &v
}

func (o GeoipConfig3) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableGeoipConfig3 struct {
	value *GeoipConfig3
	isSet bool
}

func (v NullableGeoipConfig3) Get() *GeoipConfig3 {
	return v.value
}

func (v *NullableGeoipConfig3) Set(val *GeoipConfig3) {
	v.value = val
	v.isSet = true
}

func (v NullableGeoipConfig3) IsSet() bool {
	return v.isSet
}

func (v *NullableGeoipConfig3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeoipConfig3(val *GeoipConfig3) *NullableGeoipConfig3 {
	return &NullableGeoipConfig3{value: val, isSet: true}
}

func (v NullableGeoipConfig3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeoipConfig3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


