/*
infrastructure

Infrastructure API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package infrastructure

import (
	"encoding/json"
)

// Node1 Node read summary schema.
type Node1 struct {
	// The unique fully qualified domain name (FQDN) for this node.
	Hostname string `json:"hostname"`
	// The unique identifier for a node.
	NodeId int32 `json:"nodeId"`
}

// NewNode1 instantiates a new Node1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNode1(hostname string, nodeId int32) *Node1 {
	this := Node1{}
	this.Hostname = hostname
	this.NodeId = nodeId
	return &this
}

// NewNode1WithDefaults instantiates a new Node1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNode1WithDefaults() *Node1 {
	this := Node1{}
	return &this
}

// GetHostname returns the Hostname field value
func (o *Node1) GetHostname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value
// and a boolean to check if the value has been set.
func (o *Node1) GetHostnameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Hostname, true
}

// SetHostname sets field value
func (o *Node1) SetHostname(v string) {
	o.Hostname = v
}

// GetNodeId returns the NodeId field value
func (o *Node1) GetNodeId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *Node1) GetNodeIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *Node1) SetNodeId(v int32) {
	o.NodeId = v
}

func (o Node1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["hostname"] = o.Hostname
	}
	if true {
		toSerialize["nodeId"] = o.NodeId
	}
	return json.Marshal(toSerialize)
}

type NullableNode1 struct {
	value *Node1
	isSet bool
}

func (v NullableNode1) Get() *Node1 {
	return v.value
}

func (v *NullableNode1) Set(val *Node1) {
	v.value = val
	v.isSet = true
}

func (v NullableNode1) IsSet() bool {
	return v.isSet
}

func (v *NullableNode1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNode1(val *Node1) *NullableNode1 {
	return &NullableNode1{value: val, isSet: true}
}

func (v NullableNode1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNode1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


