/*
infrastructure

Infrastructure API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package infrastructure

import (
	"encoding/json"
)

// Site2 Site summary view schema.
type Site2 struct {
	// The unique identifier for a site.
	SiteId int32 `json:"siteId"`
	// The unique name for this site.
	Name string `json:"name"`
}

// NewSite2 instantiates a new Site2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSite2(siteId int32, name string) *Site2 {
	this := Site2{}
	this.SiteId = siteId
	this.Name = name
	return &this
}

// NewSite2WithDefaults instantiates a new Site2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSite2WithDefaults() *Site2 {
	this := Site2{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *Site2) GetSiteId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *Site2) GetSiteIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *Site2) SetSiteId(v int32) {
	o.SiteId = v
}

// GetName returns the Name field value
func (o *Site2) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Site2) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Site2) SetName(v string) {
	o.Name = v
}

func (o Site2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["siteId"] = o.SiteId
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableSite2 struct {
	value *Site2
	isSet bool
}

func (v NullableSite2) Get() *Site2 {
	return v.value
}

func (v *NullableSite2) Set(val *Site2) {
	v.value = val
	v.isSet = true
}

func (v NullableSite2) IsSet() bool {
	return v.isSet
}

func (v *NullableSite2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSite2(val *Site2) *NullableSite2 {
	return &NullableSite2{value: val, isSet: true}
}

func (v NullableSite2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSite2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


