/*
infrastructure

Infrastructure API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package infrastructure

import (
	"encoding/json"
)

// NodeReadSummary Node read summary schema.
type NodeReadSummary struct {
	// The unique fully qualified domain name (FQDN) for this node.
	Hostname string `json:"hostname"`
	// The unique identifier for a node.
	NodeId int32 `json:"nodeId"`
}

// NewNodeReadSummary instantiates a new NodeReadSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodeReadSummary(hostname string, nodeId int32) *NodeReadSummary {
	this := NodeReadSummary{}
	this.Hostname = hostname
	this.NodeId = nodeId
	return &this
}

// NewNodeReadSummaryWithDefaults instantiates a new NodeReadSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeReadSummaryWithDefaults() *NodeReadSummary {
	this := NodeReadSummary{}
	return &this
}

// GetHostname returns the Hostname field value
func (o *NodeReadSummary) GetHostname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value
// and a boolean to check if the value has been set.
func (o *NodeReadSummary) GetHostnameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Hostname, true
}

// SetHostname sets field value
func (o *NodeReadSummary) SetHostname(v string) {
	o.Hostname = v
}

// GetNodeId returns the NodeId field value
func (o *NodeReadSummary) GetNodeId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *NodeReadSummary) GetNodeIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *NodeReadSummary) SetNodeId(v int32) {
	o.NodeId = v
}

func (o NodeReadSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["hostname"] = o.Hostname
	}
	if true {
		toSerialize["nodeId"] = o.NodeId
	}
	return json.Marshal(toSerialize)
}

type NullableNodeReadSummary struct {
	value *NodeReadSummary
	isSet bool
}

func (v NullableNodeReadSummary) Get() *NodeReadSummary {
	return v.value
}

func (v *NullableNodeReadSummary) Set(val *NodeReadSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeReadSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeReadSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeReadSummary(val *NodeReadSummary) *NullableNodeReadSummary {
	return &NullableNodeReadSummary{value: val, isSet: true}
}

func (v NullableNodeReadSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeReadSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


