/*
lcdn-deployment

Aura LCDN Deployment API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lcdn_deployment

import (
	"encoding/json"
)

// RequestrouterInstanceUpdate Request Router instance update schema.
type RequestrouterInstanceUpdate struct {
	// The unique identifier for a Request Router node.
	NodeId int32 `json:"nodeId"`
	ServiceLabels *ServiceLabelsType `json:"serviceLabels,omitempty"`
}

// NewRequestrouterInstanceUpdate instantiates a new RequestrouterInstanceUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestrouterInstanceUpdate(nodeId int32) *RequestrouterInstanceUpdate {
	this := RequestrouterInstanceUpdate{}
	this.NodeId = nodeId
	return &this
}

// NewRequestrouterInstanceUpdateWithDefaults instantiates a new RequestrouterInstanceUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestrouterInstanceUpdateWithDefaults() *RequestrouterInstanceUpdate {
	this := RequestrouterInstanceUpdate{}
	return &this
}

// GetNodeId returns the NodeId field value
func (o *RequestrouterInstanceUpdate) GetNodeId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *RequestrouterInstanceUpdate) GetNodeIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *RequestrouterInstanceUpdate) SetNodeId(v int32) {
	o.NodeId = v
}

// GetServiceLabels returns the ServiceLabels field value if set, zero value otherwise.
func (o *RequestrouterInstanceUpdate) GetServiceLabels() ServiceLabelsType {
	if o == nil || o.ServiceLabels == nil {
		var ret ServiceLabelsType
		return ret
	}
	return *o.ServiceLabels
}

// GetServiceLabelsOk returns a tuple with the ServiceLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestrouterInstanceUpdate) GetServiceLabelsOk() (*ServiceLabelsType, bool) {
	if o == nil || o.ServiceLabels == nil {
		return nil, false
	}
	return o.ServiceLabels, true
}

// HasServiceLabels returns a boolean if a field has been set.
func (o *RequestrouterInstanceUpdate) HasServiceLabels() bool {
	if o != nil && o.ServiceLabels != nil {
		return true
	}

	return false
}

// SetServiceLabels gets a reference to the given ServiceLabelsType and assigns it to the ServiceLabels field.
func (o *RequestrouterInstanceUpdate) SetServiceLabels(v ServiceLabelsType) {
	o.ServiceLabels = &v
}

func (o RequestrouterInstanceUpdate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["nodeId"] = o.NodeId
	}
	if o.ServiceLabels != nil {
		toSerialize["serviceLabels"] = o.ServiceLabels
	}
	return json.Marshal(toSerialize)
}

type NullableRequestrouterInstanceUpdate struct {
	value *RequestrouterInstanceUpdate
	isSet bool
}

func (v NullableRequestrouterInstanceUpdate) Get() *RequestrouterInstanceUpdate {
	return v.value
}

func (v *NullableRequestrouterInstanceUpdate) Set(val *RequestrouterInstanceUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestrouterInstanceUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestrouterInstanceUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestrouterInstanceUpdate(val *RequestrouterInstanceUpdate) *NullableRequestrouterInstanceUpdate {
	return &NullableRequestrouterInstanceUpdate{value: val, isSet: true}
}

func (v NullableRequestrouterInstanceUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestrouterInstanceUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


