/*
lcdn-deployment

Aura LCDN Deployment API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lcdn_deployment

import (
	"encoding/json"
)

// HypercacheInstanceUpdate HPC instance create or update schema.
type HypercacheInstanceUpdate struct {
	// A value that determines the maximum client-serving interface bandwidth on a node, in megabits per second. Request Router compares the bandwidth usage for each node with the maximum configured limit to help determine node availability.
	ClientServingBandwidthLimitMbps *int32 `json:"clientServingBandwidthLimitMbps,omitempty"`
	// A value that you assign to the HyperCache node to override the amount of caching memory the HyperCache node uses. Specify the value in megabytes. Recommended caching memory is 1891 megabytes out of 3783 megabytes of total memory. Improperly configuring the HyperCache caching memory can negatively affect the CDN. You should not have to override the automatically calculated memory. However, if you choose to override the caching memory, we strongly recommend that you first contact [Akamai Technical Support](https://control.akamai.com/apps/support-ui/#/contact-support).
	CachingMemoryOverrideMB *int32 `json:"cachingMemoryOverrideMB,omitempty"`
	// The unique identifier for a HyperCache node.
	NodeId int32 `json:"nodeId"`
	// The license for a particular HyperCache instance. The minimum length is 1 and the maximum length is 32767.
	License string `json:"license"`
	ServiceLabels *ServiceLabelsType1 `json:"serviceLabels,omitempty"`
}

// NewHypercacheInstanceUpdate instantiates a new HypercacheInstanceUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHypercacheInstanceUpdate(nodeId int32, license string) *HypercacheInstanceUpdate {
	this := HypercacheInstanceUpdate{}
	this.NodeId = nodeId
	this.License = license
	return &this
}

// NewHypercacheInstanceUpdateWithDefaults instantiates a new HypercacheInstanceUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHypercacheInstanceUpdateWithDefaults() *HypercacheInstanceUpdate {
	this := HypercacheInstanceUpdate{}
	return &this
}

// GetClientServingBandwidthLimitMbps returns the ClientServingBandwidthLimitMbps field value if set, zero value otherwise.
func (o *HypercacheInstanceUpdate) GetClientServingBandwidthLimitMbps() int32 {
	if o == nil || o.ClientServingBandwidthLimitMbps == nil {
		var ret int32
		return ret
	}
	return *o.ClientServingBandwidthLimitMbps
}

// GetClientServingBandwidthLimitMbpsOk returns a tuple with the ClientServingBandwidthLimitMbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypercacheInstanceUpdate) GetClientServingBandwidthLimitMbpsOk() (*int32, bool) {
	if o == nil || o.ClientServingBandwidthLimitMbps == nil {
		return nil, false
	}
	return o.ClientServingBandwidthLimitMbps, true
}

// HasClientServingBandwidthLimitMbps returns a boolean if a field has been set.
func (o *HypercacheInstanceUpdate) HasClientServingBandwidthLimitMbps() bool {
	if o != nil && o.ClientServingBandwidthLimitMbps != nil {
		return true
	}

	return false
}

// SetClientServingBandwidthLimitMbps gets a reference to the given int32 and assigns it to the ClientServingBandwidthLimitMbps field.
func (o *HypercacheInstanceUpdate) SetClientServingBandwidthLimitMbps(v int32) {
	o.ClientServingBandwidthLimitMbps = &v
}

// GetCachingMemoryOverrideMB returns the CachingMemoryOverrideMB field value if set, zero value otherwise.
func (o *HypercacheInstanceUpdate) GetCachingMemoryOverrideMB() int32 {
	if o == nil || o.CachingMemoryOverrideMB == nil {
		var ret int32
		return ret
	}
	return *o.CachingMemoryOverrideMB
}

// GetCachingMemoryOverrideMBOk returns a tuple with the CachingMemoryOverrideMB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypercacheInstanceUpdate) GetCachingMemoryOverrideMBOk() (*int32, bool) {
	if o == nil || o.CachingMemoryOverrideMB == nil {
		return nil, false
	}
	return o.CachingMemoryOverrideMB, true
}

// HasCachingMemoryOverrideMB returns a boolean if a field has been set.
func (o *HypercacheInstanceUpdate) HasCachingMemoryOverrideMB() bool {
	if o != nil && o.CachingMemoryOverrideMB != nil {
		return true
	}

	return false
}

// SetCachingMemoryOverrideMB gets a reference to the given int32 and assigns it to the CachingMemoryOverrideMB field.
func (o *HypercacheInstanceUpdate) SetCachingMemoryOverrideMB(v int32) {
	o.CachingMemoryOverrideMB = &v
}

// GetNodeId returns the NodeId field value
func (o *HypercacheInstanceUpdate) GetNodeId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *HypercacheInstanceUpdate) GetNodeIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *HypercacheInstanceUpdate) SetNodeId(v int32) {
	o.NodeId = v
}

// GetLicense returns the License field value
func (o *HypercacheInstanceUpdate) GetLicense() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.License
}

// GetLicenseOk returns a tuple with the License field value
// and a boolean to check if the value has been set.
func (o *HypercacheInstanceUpdate) GetLicenseOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.License, true
}

// SetLicense sets field value
func (o *HypercacheInstanceUpdate) SetLicense(v string) {
	o.License = v
}

// GetServiceLabels returns the ServiceLabels field value if set, zero value otherwise.
func (o *HypercacheInstanceUpdate) GetServiceLabels() ServiceLabelsType1 {
	if o == nil || o.ServiceLabels == nil {
		var ret ServiceLabelsType1
		return ret
	}
	return *o.ServiceLabels
}

// GetServiceLabelsOk returns a tuple with the ServiceLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypercacheInstanceUpdate) GetServiceLabelsOk() (*ServiceLabelsType1, bool) {
	if o == nil || o.ServiceLabels == nil {
		return nil, false
	}
	return o.ServiceLabels, true
}

// HasServiceLabels returns a boolean if a field has been set.
func (o *HypercacheInstanceUpdate) HasServiceLabels() bool {
	if o != nil && o.ServiceLabels != nil {
		return true
	}

	return false
}

// SetServiceLabels gets a reference to the given ServiceLabelsType1 and assigns it to the ServiceLabels field.
func (o *HypercacheInstanceUpdate) SetServiceLabels(v ServiceLabelsType1) {
	o.ServiceLabels = &v
}

func (o HypercacheInstanceUpdate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ClientServingBandwidthLimitMbps != nil {
		toSerialize["clientServingBandwidthLimitMbps"] = o.ClientServingBandwidthLimitMbps
	}
	if o.CachingMemoryOverrideMB != nil {
		toSerialize["cachingMemoryOverrideMB"] = o.CachingMemoryOverrideMB
	}
	if true {
		toSerialize["nodeId"] = o.NodeId
	}
	if true {
		toSerialize["license"] = o.License
	}
	if o.ServiceLabels != nil {
		toSerialize["serviceLabels"] = o.ServiceLabels
	}
	return json.Marshal(toSerialize)
}

type NullableHypercacheInstanceUpdate struct {
	value *HypercacheInstanceUpdate
	isSet bool
}

func (v NullableHypercacheInstanceUpdate) Get() *HypercacheInstanceUpdate {
	return v.value
}

func (v *NullableHypercacheInstanceUpdate) Set(val *HypercacheInstanceUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableHypercacheInstanceUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableHypercacheInstanceUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHypercacheInstanceUpdate(val *HypercacheInstanceUpdate) *NullableHypercacheInstanceUpdate {
	return &NullableHypercacheInstanceUpdate{value: val, isSet: true}
}

func (v NullableHypercacheInstanceUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHypercacheInstanceUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


