/*
lcdn-deployment

Aura LCDN Deployment API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lcdn_deployment

import (
	"encoding/json"
)

// HypercacheInstance3 HPC instance collection.
type HypercacheInstance3 struct {
	Instances []HypercacheInstance `json:"instances"`
	Page PageType `json:"page"`
}

// NewHypercacheInstance3 instantiates a new HypercacheInstance3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHypercacheInstance3(instances []HypercacheInstance, page PageType) *HypercacheInstance3 {
	this := HypercacheInstance3{}
	this.Instances = instances
	this.Page = page
	return &this
}

// NewHypercacheInstance3WithDefaults instantiates a new HypercacheInstance3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHypercacheInstance3WithDefaults() *HypercacheInstance3 {
	this := HypercacheInstance3{}
	return &this
}

// GetInstances returns the Instances field value
func (o *HypercacheInstance3) GetInstances() []HypercacheInstance {
	if o == nil {
		var ret []HypercacheInstance
		return ret
	}

	return o.Instances
}

// GetInstancesOk returns a tuple with the Instances field value
// and a boolean to check if the value has been set.
func (o *HypercacheInstance3) GetInstancesOk() (*[]HypercacheInstance, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Instances, true
}

// SetInstances sets field value
func (o *HypercacheInstance3) SetInstances(v []HypercacheInstance) {
	o.Instances = v
}

// GetPage returns the Page field value
func (o *HypercacheInstance3) GetPage() PageType {
	if o == nil {
		var ret PageType
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *HypercacheInstance3) GetPageOk() (*PageType, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *HypercacheInstance3) SetPage(v PageType) {
	o.Page = v
}

func (o HypercacheInstance3) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["instances"] = o.Instances
	}
	if true {
		toSerialize["page"] = o.Page
	}
	return json.Marshal(toSerialize)
}

type NullableHypercacheInstance3 struct {
	value *HypercacheInstance3
	isSet bool
}

func (v NullableHypercacheInstance3) Get() *HypercacheInstance3 {
	return v.value
}

func (v *NullableHypercacheInstance3) Set(val *HypercacheInstance3) {
	v.value = val
	v.isSet = true
}

func (v NullableHypercacheInstance3) IsSet() bool {
	return v.isSet
}

func (v *NullableHypercacheInstance3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHypercacheInstance3(val *HypercacheInstance3) *NullableHypercacheInstance3 {
	return &NullableHypercacheInstance3{value: val, isSet: true}
}

func (v NullableHypercacheInstance3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHypercacheInstance3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


