/*
content-delivery

Aura LCDN Content Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// LastMileAcceleration Compress contents using GZIP before sending them out from edge HyperCaches to supported clients.
type LastMileAcceleration struct {
	// The name of the behavior, `lastMileAcceleration` in this case.
	Name string `json:"name"`
	Options LastMileAccelerationOptions `json:"options"`
}

// NewLastMileAcceleration instantiates a new LastMileAcceleration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLastMileAcceleration(name string, options LastMileAccelerationOptions) *LastMileAcceleration {
	this := LastMileAcceleration{}
	this.Name = name
	this.Options = options
	return &this
}

// NewLastMileAccelerationWithDefaults instantiates a new LastMileAcceleration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLastMileAccelerationWithDefaults() *LastMileAcceleration {
	this := LastMileAcceleration{}
	return &this
}

// GetName returns the Name field value
func (o *LastMileAcceleration) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LastMileAcceleration) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LastMileAcceleration) SetName(v string) {
	o.Name = v
}

// GetOptions returns the Options field value
func (o *LastMileAcceleration) GetOptions() LastMileAccelerationOptions {
	if o == nil {
		var ret LastMileAccelerationOptions
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *LastMileAcceleration) GetOptionsOk() (*LastMileAccelerationOptions, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Options, true
}

// SetOptions sets field value
func (o *LastMileAcceleration) SetOptions(v LastMileAccelerationOptions) {
	o.Options = v
}

func (o LastMileAcceleration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["options"] = o.Options
	}
	return json.Marshal(toSerialize)
}

type NullableLastMileAcceleration struct {
	value *LastMileAcceleration
	isSet bool
}

func (v NullableLastMileAcceleration) Get() *LastMileAcceleration {
	return v.value
}

func (v *NullableLastMileAcceleration) Set(val *LastMileAcceleration) {
	v.value = val
	v.isSet = true
}

func (v NullableLastMileAcceleration) IsSet() bool {
	return v.isSet
}

func (v *NullableLastMileAcceleration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLastMileAcceleration(val *LastMileAcceleration) *NullableLastMileAcceleration {
	return &NullableLastMileAcceleration{value: val, isSet: true}
}

func (v NullableLastMileAcceleration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLastMileAcceleration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


