/*
content-delivery

Cotent Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// OriginCollection Origin collection
type OriginCollection struct {
	Page PageType `json:"page"`
	Origins []Origin3 `json:"origins"`
}

// NewOriginCollection instantiates a new OriginCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOriginCollection(page PageType, origins []Origin3) *OriginCollection {
	this := OriginCollection{}
	this.Page = page
	this.Origins = origins
	return &this
}

// NewOriginCollectionWithDefaults instantiates a new OriginCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOriginCollectionWithDefaults() *OriginCollection {
	this := OriginCollection{}
	return &this
}

// GetPage returns the Page field value
func (o *OriginCollection) GetPage() PageType {
	if o == nil {
		var ret PageType
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *OriginCollection) GetPageOk() (*PageType, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *OriginCollection) SetPage(v PageType) {
	o.Page = v
}

// GetOrigins returns the Origins field value
func (o *OriginCollection) GetOrigins() []Origin3 {
	if o == nil {
		var ret []Origin3
		return ret
	}

	return o.Origins
}

// GetOriginsOk returns a tuple with the Origins field value
// and a boolean to check if the value has been set.
func (o *OriginCollection) GetOriginsOk() (*[]Origin3, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Origins, true
}

// SetOrigins sets field value
func (o *OriginCollection) SetOrigins(v []Origin3) {
	o.Origins = v
}

func (o OriginCollection) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["page"] = o.Page
	}
	if true {
		toSerialize["origins"] = o.Origins
	}
	return json.Marshal(toSerialize)
}

type NullableOriginCollection struct {
	value *OriginCollection
	isSet bool
}

func (v NullableOriginCollection) Get() *OriginCollection {
	return v.value
}

func (v *NullableOriginCollection) Set(val *OriginCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableOriginCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableOriginCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOriginCollection(val *OriginCollection) *NullableOriginCollection {
	return &NullableOriginCollection{value: val, isSet: true}
}

func (v NullableOriginCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOriginCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


