/*
content-delivery

Cotent Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// Cors Configuration of Cross-Origin Resource Sharing (CORS) response headers at the HyperCache for this rule.
type Cors struct {
	// The name of the behavior, `cors` in this case.
	Name string `json:"name"`
	Options CorsOptions `json:"options"`
}

// NewCors instantiates a new Cors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCors(name string, options CorsOptions) *Cors {
	this := Cors{}
	this.Name = name
	this.Options = options
	return &this
}

// NewCorsWithDefaults instantiates a new Cors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCorsWithDefaults() *Cors {
	this := Cors{}
	return &this
}

// GetName returns the Name field value
func (o *Cors) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Cors) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Cors) SetName(v string) {
	o.Name = v
}

// GetOptions returns the Options field value
func (o *Cors) GetOptions() CorsOptions {
	if o == nil {
		var ret CorsOptions
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *Cors) GetOptionsOk() (*CorsOptions, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Options, true
}

// SetOptions sets field value
func (o *Cors) SetOptions(v CorsOptions) {
	o.Options = v
}

func (o Cors) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["options"] = o.Options
	}
	return json.Marshal(toSerialize)
}

type NullableCors struct {
	value *Cors
	isSet bool
}

func (v NullableCors) Get() *Cors {
	return v.value
}

func (v *NullableCors) Set(val *Cors) {
	v.value = val
	v.isSet = true
}

func (v NullableCors) IsSet() bool {
	return v.isSet
}

func (v *NullableCors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCors(val *Cors) *NullableCors {
	return &NullableCors{value: val, isSet: true}
}

func (v NullableCors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


