/*
content-delivery

Cotent Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// SharedSecretSetReadDetailed Shared secret set object schema definition.  Shared secrets are used for URI signing, which is used as an authorization method for content delivery.
type SharedSecretSetReadDetailed struct {
	ContentProviderId int32 `json:"contentProviderId"`
	Name string `json:"name"`
	SharedSecretSetId int32 `json:"sharedSecretSetId"`
}

// NewSharedSecretSetReadDetailed instantiates a new SharedSecretSetReadDetailed object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSharedSecretSetReadDetailed(contentProviderId int32, name string, sharedSecretSetId int32) *SharedSecretSetReadDetailed {
	this := SharedSecretSetReadDetailed{}
	this.ContentProviderId = contentProviderId
	this.Name = name
	this.SharedSecretSetId = sharedSecretSetId
	return &this
}

// NewSharedSecretSetReadDetailedWithDefaults instantiates a new SharedSecretSetReadDetailed object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSharedSecretSetReadDetailedWithDefaults() *SharedSecretSetReadDetailed {
	this := SharedSecretSetReadDetailed{}
	return &this
}

// GetContentProviderId returns the ContentProviderId field value
func (o *SharedSecretSetReadDetailed) GetContentProviderId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ContentProviderId
}

// GetContentProviderIdOk returns a tuple with the ContentProviderId field value
// and a boolean to check if the value has been set.
func (o *SharedSecretSetReadDetailed) GetContentProviderIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ContentProviderId, true
}

// SetContentProviderId sets field value
func (o *SharedSecretSetReadDetailed) SetContentProviderId(v int32) {
	o.ContentProviderId = v
}

// GetName returns the Name field value
func (o *SharedSecretSetReadDetailed) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SharedSecretSetReadDetailed) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SharedSecretSetReadDetailed) SetName(v string) {
	o.Name = v
}

// GetSharedSecretSetId returns the SharedSecretSetId field value
func (o *SharedSecretSetReadDetailed) GetSharedSecretSetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SharedSecretSetId
}

// GetSharedSecretSetIdOk returns a tuple with the SharedSecretSetId field value
// and a boolean to check if the value has been set.
func (o *SharedSecretSetReadDetailed) GetSharedSecretSetIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SharedSecretSetId, true
}

// SetSharedSecretSetId sets field value
func (o *SharedSecretSetReadDetailed) SetSharedSecretSetId(v int32) {
	o.SharedSecretSetId = v
}

func (o SharedSecretSetReadDetailed) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["contentProviderId"] = o.ContentProviderId
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["sharedSecretSetId"] = o.SharedSecretSetId
	}
	return json.Marshal(toSerialize)
}

type NullableSharedSecretSetReadDetailed struct {
	value *SharedSecretSetReadDetailed
	isSet bool
}

func (v NullableSharedSecretSetReadDetailed) Get() *SharedSecretSetReadDetailed {
	return v.value
}

func (v *NullableSharedSecretSetReadDetailed) Set(val *SharedSecretSetReadDetailed) {
	v.value = val
	v.isSet = true
}

func (v NullableSharedSecretSetReadDetailed) IsSet() bool {
	return v.isSet
}

func (v *NullableSharedSecretSetReadDetailed) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSharedSecretSetReadDetailed(val *SharedSecretSetReadDetailed) *NullableSharedSecretSetReadDetailed {
	return &NullableSharedSecretSetReadDetailed{value: val, isSet: true}
}

func (v NullableSharedSecretSetReadDetailed) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSharedSecretSetReadDetailed) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


