/*
content-delivery

Aura LCDN Content Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// SharedSecretSetUpdate Shared secret set object schema definition.  Shared secrets are used for URI signing, which is used as an authorization method for content delivery.
type SharedSecretSetUpdate struct {
	ContentProviderId int32 `json:"contentProviderId"`
	Name string `json:"name"`
	SharedSecretSetId int32 `json:"sharedSecretSetId"`
}

// NewSharedSecretSetUpdate instantiates a new SharedSecretSetUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSharedSecretSetUpdate(contentProviderId int32, name string, sharedSecretSetId int32) *SharedSecretSetUpdate {
	this := SharedSecretSetUpdate{}
	this.ContentProviderId = contentProviderId
	this.Name = name
	this.SharedSecretSetId = sharedSecretSetId
	return &this
}

// NewSharedSecretSetUpdateWithDefaults instantiates a new SharedSecretSetUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSharedSecretSetUpdateWithDefaults() *SharedSecretSetUpdate {
	this := SharedSecretSetUpdate{}
	return &this
}

// GetContentProviderId returns the ContentProviderId field value
func (o *SharedSecretSetUpdate) GetContentProviderId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ContentProviderId
}

// GetContentProviderIdOk returns a tuple with the ContentProviderId field value
// and a boolean to check if the value has been set.
func (o *SharedSecretSetUpdate) GetContentProviderIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ContentProviderId, true
}

// SetContentProviderId sets field value
func (o *SharedSecretSetUpdate) SetContentProviderId(v int32) {
	o.ContentProviderId = v
}

// GetName returns the Name field value
func (o *SharedSecretSetUpdate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SharedSecretSetUpdate) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SharedSecretSetUpdate) SetName(v string) {
	o.Name = v
}

// GetSharedSecretSetId returns the SharedSecretSetId field value
func (o *SharedSecretSetUpdate) GetSharedSecretSetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SharedSecretSetId
}

// GetSharedSecretSetIdOk returns a tuple with the SharedSecretSetId field value
// and a boolean to check if the value has been set.
func (o *SharedSecretSetUpdate) GetSharedSecretSetIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SharedSecretSetId, true
}

// SetSharedSecretSetId sets field value
func (o *SharedSecretSetUpdate) SetSharedSecretSetId(v int32) {
	o.SharedSecretSetId = v
}

func (o SharedSecretSetUpdate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["contentProviderId"] = o.ContentProviderId
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["sharedSecretSetId"] = o.SharedSecretSetId
	}
	return json.Marshal(toSerialize)
}

type NullableSharedSecretSetUpdate struct {
	value *SharedSecretSetUpdate
	isSet bool
}

func (v NullableSharedSecretSetUpdate) Get() *SharedSecretSetUpdate {
	return v.value
}

func (v *NullableSharedSecretSetUpdate) Set(val *SharedSecretSetUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableSharedSecretSetUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableSharedSecretSetUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSharedSecretSetUpdate(val *SharedSecretSetUpdate) *NullableSharedSecretSetUpdate {
	return &NullableSharedSecretSetUpdate{value: val, isSet: true}
}

func (v NullableSharedSecretSetUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSharedSecretSetUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


