/*
content-delivery

Aura LCDN Content Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// SiteRedirectTypeOptions This behavior's set of configuration options.
type SiteRedirectTypeOptions struct {
	// Whether to look at `CLIENT_IP` or `SITE` information when redirecting requests.
	Value string `json:"value"`
}

// NewSiteRedirectTypeOptions instantiates a new SiteRedirectTypeOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteRedirectTypeOptions(value string) *SiteRedirectTypeOptions {
	this := SiteRedirectTypeOptions{}
	this.Value = value
	return &this
}

// NewSiteRedirectTypeOptionsWithDefaults instantiates a new SiteRedirectTypeOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteRedirectTypeOptionsWithDefaults() *SiteRedirectTypeOptions {
	this := SiteRedirectTypeOptions{}
	return &this
}

// GetValue returns the Value field value
func (o *SiteRedirectTypeOptions) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *SiteRedirectTypeOptions) GetValueOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *SiteRedirectTypeOptions) SetValue(v string) {
	o.Value = v
}

func (o SiteRedirectTypeOptions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableSiteRedirectTypeOptions struct {
	value *SiteRedirectTypeOptions
	isSet bool
}

func (v NullableSiteRedirectTypeOptions) Get() *SiteRedirectTypeOptions {
	return v.value
}

func (v *NullableSiteRedirectTypeOptions) Set(val *SiteRedirectTypeOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteRedirectTypeOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteRedirectTypeOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteRedirectTypeOptions(val *SiteRedirectTypeOptions) *NullableSiteRedirectTypeOptions {
	return &NullableSiteRedirectTypeOptions{value: val, isSet: true}
}

func (v NullableSiteRedirectTypeOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteRedirectTypeOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


