/*
content-delivery

Aura LCDN Content Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// DefaultHttp2DeliveryOptions This behavior's set of configuration options.
type DefaultHttp2DeliveryOptions struct {
	// Enables default HTTP2 Delivery for this prefix.
	Enable bool `json:"enable"`
}

// NewDefaultHttp2DeliveryOptions instantiates a new DefaultHttp2DeliveryOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultHttp2DeliveryOptions(enable bool) *DefaultHttp2DeliveryOptions {
	this := DefaultHttp2DeliveryOptions{}
	this.Enable = enable
	return &this
}

// NewDefaultHttp2DeliveryOptionsWithDefaults instantiates a new DefaultHttp2DeliveryOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultHttp2DeliveryOptionsWithDefaults() *DefaultHttp2DeliveryOptions {
	this := DefaultHttp2DeliveryOptions{}
	return &this
}

// GetEnable returns the Enable field value
func (o *DefaultHttp2DeliveryOptions) GetEnable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enable
}

// GetEnableOk returns a tuple with the Enable field value
// and a boolean to check if the value has been set.
func (o *DefaultHttp2DeliveryOptions) GetEnableOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Enable, true
}

// SetEnable sets field value
func (o *DefaultHttp2DeliveryOptions) SetEnable(v bool) {
	o.Enable = v
}

func (o DefaultHttp2DeliveryOptions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["enable"] = o.Enable
	}
	return json.Marshal(toSerialize)
}

type NullableDefaultHttp2DeliveryOptions struct {
	value *DefaultHttp2DeliveryOptions
	isSet bool
}

func (v NullableDefaultHttp2DeliveryOptions) Get() *DefaultHttp2DeliveryOptions {
	return v.value
}

func (v *NullableDefaultHttp2DeliveryOptions) Set(val *DefaultHttp2DeliveryOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultHttp2DeliveryOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultHttp2DeliveryOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultHttp2DeliveryOptions(val *DefaultHttp2DeliveryOptions) *NullableDefaultHttp2DeliveryOptions {
	return &NullableDefaultHttp2DeliveryOptions{value: val, isSet: true}
}

func (v NullableDefaultHttp2DeliveryOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultHttp2DeliveryOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


