/*
content-delivery

Cotent Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// HttpsDelivery Override default setting for HTTPS delivery.
type HttpsDelivery struct {
	// The name of the behavior, `httpsDelivery` in this case.
	Name string `json:"name"`
	Options HttpDeliveryOptions `json:"options"`
}

// NewHttpsDelivery instantiates a new HttpsDelivery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHttpsDelivery(name string, options HttpDeliveryOptions) *HttpsDelivery {
	this := HttpsDelivery{}
	this.Name = name
	this.Options = options
	return &this
}

// NewHttpsDeliveryWithDefaults instantiates a new HttpsDelivery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHttpsDeliveryWithDefaults() *HttpsDelivery {
	this := HttpsDelivery{}
	return &this
}

// GetName returns the Name field value
func (o *HttpsDelivery) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HttpsDelivery) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HttpsDelivery) SetName(v string) {
	o.Name = v
}

// GetOptions returns the Options field value
func (o *HttpsDelivery) GetOptions() HttpDeliveryOptions {
	if o == nil {
		var ret HttpDeliveryOptions
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *HttpsDelivery) GetOptionsOk() (*HttpDeliveryOptions, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Options, true
}

// SetOptions sets field value
func (o *HttpsDelivery) SetOptions(v HttpDeliveryOptions) {
	o.Options = v
}

func (o HttpsDelivery) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["options"] = o.Options
	}
	return json.Marshal(toSerialize)
}

type NullableHttpsDelivery struct {
	value *HttpsDelivery
	isSet bool
}

func (v NullableHttpsDelivery) Get() *HttpsDelivery {
	return v.value
}

func (v *NullableHttpsDelivery) Set(val *HttpsDelivery) {
	v.value = val
	v.isSet = true
}

func (v NullableHttpsDelivery) IsSet() bool {
	return v.isSet
}

func (v *NullableHttpsDelivery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHttpsDelivery(val *HttpsDelivery) *NullableHttpsDelivery {
	return &NullableHttpsDelivery{value: val, isSet: true}
}

func (v NullableHttpsDelivery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHttpsDelivery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


