/*
content-delivery

Cotent Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// OriginRangeRequestOptions This behavior's set of configuration options.
type OriginRangeRequestOptions struct {
	// When enabled, allows range requests to the origin.
	Enable bool `json:"enable"`
}

// NewOriginRangeRequestOptions instantiates a new OriginRangeRequestOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOriginRangeRequestOptions(enable bool) *OriginRangeRequestOptions {
	this := OriginRangeRequestOptions{}
	this.Enable = enable
	return &this
}

// NewOriginRangeRequestOptionsWithDefaults instantiates a new OriginRangeRequestOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOriginRangeRequestOptionsWithDefaults() *OriginRangeRequestOptions {
	this := OriginRangeRequestOptions{}
	return &this
}

// GetEnable returns the Enable field value
func (o *OriginRangeRequestOptions) GetEnable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enable
}

// GetEnableOk returns a tuple with the Enable field value
// and a boolean to check if the value has been set.
func (o *OriginRangeRequestOptions) GetEnableOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Enable, true
}

// SetEnable sets field value
func (o *OriginRangeRequestOptions) SetEnable(v bool) {
	o.Enable = v
}

func (o OriginRangeRequestOptions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["enable"] = o.Enable
	}
	return json.Marshal(toSerialize)
}

type NullableOriginRangeRequestOptions struct {
	value *OriginRangeRequestOptions
	isSet bool
}

func (v NullableOriginRangeRequestOptions) Get() *OriginRangeRequestOptions {
	return v.value
}

func (v *NullableOriginRangeRequestOptions) Set(val *OriginRangeRequestOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableOriginRangeRequestOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableOriginRangeRequestOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOriginRangeRequestOptions(val *OriginRangeRequestOptions) *NullableOriginRangeRequestOptions {
	return &NullableOriginRangeRequestOptions{value: val, isSet: true}
}

func (v NullableOriginRangeRequestOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOriginRangeRequestOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


