/*
content-delivery

Cotent Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// FollowRedirect Control the behavior of the HyperCache when it receives a 302 Redirect from the Origin.
type FollowRedirect struct {
	// The name of the behavior, `followRedirect` in this case.
	Name string `json:"name"`
	Options FollowRedirectOptions `json:"options"`
}

// NewFollowRedirect instantiates a new FollowRedirect object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFollowRedirect(name string, options FollowRedirectOptions) *FollowRedirect {
	this := FollowRedirect{}
	this.Name = name
	this.Options = options
	return &this
}

// NewFollowRedirectWithDefaults instantiates a new FollowRedirect object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFollowRedirectWithDefaults() *FollowRedirect {
	this := FollowRedirect{}
	return &this
}

// GetName returns the Name field value
func (o *FollowRedirect) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FollowRedirect) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FollowRedirect) SetName(v string) {
	o.Name = v
}

// GetOptions returns the Options field value
func (o *FollowRedirect) GetOptions() FollowRedirectOptions {
	if o == nil {
		var ret FollowRedirectOptions
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *FollowRedirect) GetOptionsOk() (*FollowRedirectOptions, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Options, true
}

// SetOptions sets field value
func (o *FollowRedirect) SetOptions(v FollowRedirectOptions) {
	o.Options = v
}

func (o FollowRedirect) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["options"] = o.Options
	}
	return json.Marshal(toSerialize)
}

type NullableFollowRedirect struct {
	value *FollowRedirect
	isSet bool
}

func (v NullableFollowRedirect) Get() *FollowRedirect {
	return v.value
}

func (v *NullableFollowRedirect) Set(val *FollowRedirect) {
	v.value = val
	v.isSet = true
}

func (v NullableFollowRedirect) IsSet() bool {
	return v.isSet
}

func (v *NullableFollowRedirect) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFollowRedirect(val *FollowRedirect) *NullableFollowRedirect {
	return &NullableFollowRedirect{value: val, isSet: true}
}

func (v NullableFollowRedirect) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFollowRedirect) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


