/*
content-delivery

Cotent Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// HttpDelivery Override default setting for HTTP delivery.
type HttpDelivery struct {
	// The name of the behavior, `httpDelivery` in this case.
	Name string `json:"name"`
	Options HttpDeliveryOptions `json:"options"`
}

// NewHttpDelivery instantiates a new HttpDelivery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHttpDelivery(name string, options HttpDeliveryOptions) *HttpDelivery {
	this := HttpDelivery{}
	this.Name = name
	this.Options = options
	return &this
}

// NewHttpDeliveryWithDefaults instantiates a new HttpDelivery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHttpDeliveryWithDefaults() *HttpDelivery {
	this := HttpDelivery{}
	return &this
}

// GetName returns the Name field value
func (o *HttpDelivery) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HttpDelivery) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HttpDelivery) SetName(v string) {
	o.Name = v
}

// GetOptions returns the Options field value
func (o *HttpDelivery) GetOptions() HttpDeliveryOptions {
	if o == nil {
		var ret HttpDeliveryOptions
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *HttpDelivery) GetOptionsOk() (*HttpDeliveryOptions, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Options, true
}

// SetOptions sets field value
func (o *HttpDelivery) SetOptions(v HttpDeliveryOptions) {
	o.Options = v
}

func (o HttpDelivery) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["options"] = o.Options
	}
	return json.Marshal(toSerialize)
}

type NullableHttpDelivery struct {
	value *HttpDelivery
	isSet bool
}

func (v NullableHttpDelivery) Get() *HttpDelivery {
	return v.value
}

func (v *NullableHttpDelivery) Set(val *HttpDelivery) {
	v.value = val
	v.isSet = true
}

func (v NullableHttpDelivery) IsSet() bool {
	return v.isSet
}

func (v *NullableHttpDelivery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHttpDelivery(val *HttpDelivery) *NullableHttpDelivery {
	return &NullableHttpDelivery{value: val, isSet: true}
}

func (v NullableHttpDelivery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHttpDelivery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


