/*
content-delivery

Aura LCDN Content Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// UdpSyslogAccessLog Parameters associated with UDP Syslog access log feature.
type UdpSyslogAccessLog struct {
	// The name of the behavior, `udpSyslogAccessLog` in this case.
	Name string `json:"name"`
	Options UdpSyslogAccessLogOptions `json:"options"`
}

// NewUdpSyslogAccessLog instantiates a new UdpSyslogAccessLog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUdpSyslogAccessLog(name string, options UdpSyslogAccessLogOptions) *UdpSyslogAccessLog {
	this := UdpSyslogAccessLog{}
	this.Name = name
	this.Options = options
	return &this
}

// NewUdpSyslogAccessLogWithDefaults instantiates a new UdpSyslogAccessLog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUdpSyslogAccessLogWithDefaults() *UdpSyslogAccessLog {
	this := UdpSyslogAccessLog{}
	return &this
}

// GetName returns the Name field value
func (o *UdpSyslogAccessLog) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UdpSyslogAccessLog) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UdpSyslogAccessLog) SetName(v string) {
	o.Name = v
}

// GetOptions returns the Options field value
func (o *UdpSyslogAccessLog) GetOptions() UdpSyslogAccessLogOptions {
	if o == nil {
		var ret UdpSyslogAccessLogOptions
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *UdpSyslogAccessLog) GetOptionsOk() (*UdpSyslogAccessLogOptions, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Options, true
}

// SetOptions sets field value
func (o *UdpSyslogAccessLog) SetOptions(v UdpSyslogAccessLogOptions) {
	o.Options = v
}

func (o UdpSyslogAccessLog) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["options"] = o.Options
	}
	return json.Marshal(toSerialize)
}

type NullableUdpSyslogAccessLog struct {
	value *UdpSyslogAccessLog
	isSet bool
}

func (v NullableUdpSyslogAccessLog) Get() *UdpSyslogAccessLog {
	return v.value
}

func (v *NullableUdpSyslogAccessLog) Set(val *UdpSyslogAccessLog) {
	v.value = val
	v.isSet = true
}

func (v NullableUdpSyslogAccessLog) IsSet() bool {
	return v.isSet
}

func (v *NullableUdpSyslogAccessLog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUdpSyslogAccessLog(val *UdpSyslogAccessLog) *NullableUdpSyslogAccessLog {
	return &NullableUdpSyslogAccessLog{value: val, isSet: true}
}

func (v NullableUdpSyslogAccessLog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUdpSyslogAccessLog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


