/*
content-delivery

Aura LCDN Content Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// TlsDeliveryProfile A list of TLS delivery profiles.
type TlsDeliveryProfile struct {
	TlsDeliveryProfiles []TlsDeliveryProfile3 `json:"tlsDeliveryProfiles"`
	Page PageType `json:"page"`
}

// NewTlsDeliveryProfile instantiates a new TlsDeliveryProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTlsDeliveryProfile(tlsDeliveryProfiles []TlsDeliveryProfile3, page PageType) *TlsDeliveryProfile {
	this := TlsDeliveryProfile{}
	this.TlsDeliveryProfiles = tlsDeliveryProfiles
	this.Page = page
	return &this
}

// NewTlsDeliveryProfileWithDefaults instantiates a new TlsDeliveryProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTlsDeliveryProfileWithDefaults() *TlsDeliveryProfile {
	this := TlsDeliveryProfile{}
	return &this
}

// GetTlsDeliveryProfiles returns the TlsDeliveryProfiles field value
func (o *TlsDeliveryProfile) GetTlsDeliveryProfiles() []TlsDeliveryProfile3 {
	if o == nil {
		var ret []TlsDeliveryProfile3
		return ret
	}

	return o.TlsDeliveryProfiles
}

// GetTlsDeliveryProfilesOk returns a tuple with the TlsDeliveryProfiles field value
// and a boolean to check if the value has been set.
func (o *TlsDeliveryProfile) GetTlsDeliveryProfilesOk() (*[]TlsDeliveryProfile3, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TlsDeliveryProfiles, true
}

// SetTlsDeliveryProfiles sets field value
func (o *TlsDeliveryProfile) SetTlsDeliveryProfiles(v []TlsDeliveryProfile3) {
	o.TlsDeliveryProfiles = v
}

// GetPage returns the Page field value
func (o *TlsDeliveryProfile) GetPage() PageType {
	if o == nil {
		var ret PageType
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *TlsDeliveryProfile) GetPageOk() (*PageType, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *TlsDeliveryProfile) SetPage(v PageType) {
	o.Page = v
}

func (o TlsDeliveryProfile) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["tlsDeliveryProfiles"] = o.TlsDeliveryProfiles
	}
	if true {
		toSerialize["page"] = o.Page
	}
	return json.Marshal(toSerialize)
}

type NullableTlsDeliveryProfile struct {
	value *TlsDeliveryProfile
	isSet bool
}

func (v NullableTlsDeliveryProfile) Get() *TlsDeliveryProfile {
	return v.value
}

func (v *NullableTlsDeliveryProfile) Set(val *TlsDeliveryProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableTlsDeliveryProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableTlsDeliveryProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTlsDeliveryProfile(val *TlsDeliveryProfile) *NullableTlsDeliveryProfile {
	return &NullableTlsDeliveryProfile{value: val, isSet: true}
}

func (v NullableTlsDeliveryProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTlsDeliveryProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


