/*
content-delivery

Aura LCDN Content Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// DefaultHttpDeliveryOptions This behavior's set of configuration options.
type DefaultHttpDeliveryOptions struct {
	// Enables default HTTP Delivery for this prefix.
	Enable bool `json:"enable"`
}

// NewDefaultHttpDeliveryOptions instantiates a new DefaultHttpDeliveryOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultHttpDeliveryOptions(enable bool) *DefaultHttpDeliveryOptions {
	this := DefaultHttpDeliveryOptions{}
	this.Enable = enable
	return &this
}

// NewDefaultHttpDeliveryOptionsWithDefaults instantiates a new DefaultHttpDeliveryOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultHttpDeliveryOptionsWithDefaults() *DefaultHttpDeliveryOptions {
	this := DefaultHttpDeliveryOptions{}
	return &this
}

// GetEnable returns the Enable field value
func (o *DefaultHttpDeliveryOptions) GetEnable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enable
}

// GetEnableOk returns a tuple with the Enable field value
// and a boolean to check if the value has been set.
func (o *DefaultHttpDeliveryOptions) GetEnableOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Enable, true
}

// SetEnable sets field value
func (o *DefaultHttpDeliveryOptions) SetEnable(v bool) {
	o.Enable = v
}

func (o DefaultHttpDeliveryOptions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["enable"] = o.Enable
	}
	return json.Marshal(toSerialize)
}

type NullableDefaultHttpDeliveryOptions struct {
	value *DefaultHttpDeliveryOptions
	isSet bool
}

func (v NullableDefaultHttpDeliveryOptions) Get() *DefaultHttpDeliveryOptions {
	return v.value
}

func (v *NullableDefaultHttpDeliveryOptions) Set(val *DefaultHttpDeliveryOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultHttpDeliveryOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultHttpDeliveryOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultHttpDeliveryOptions(val *DefaultHttpDeliveryOptions) *NullableDefaultHttpDeliveryOptions {
	return &NullableDefaultHttpDeliveryOptions{value: val, isSet: true}
}

func (v NullableDefaultHttpDeliveryOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultHttpDeliveryOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


