/*
content-delivery

Aura LCDN Content Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// ContentProvider2 A Content Provider summary view.
type ContentProvider2 struct {
	ContentProviderId int32 `json:"contentProviderId"`
	Name string `json:"name"`
}

// NewContentProvider2 instantiates a new ContentProvider2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentProvider2(contentProviderId int32, name string) *ContentProvider2 {
	this := ContentProvider2{}
	this.ContentProviderId = contentProviderId
	this.Name = name
	return &this
}

// NewContentProvider2WithDefaults instantiates a new ContentProvider2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentProvider2WithDefaults() *ContentProvider2 {
	this := ContentProvider2{}
	return &this
}

// GetContentProviderId returns the ContentProviderId field value
func (o *ContentProvider2) GetContentProviderId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ContentProviderId
}

// GetContentProviderIdOk returns a tuple with the ContentProviderId field value
// and a boolean to check if the value has been set.
func (o *ContentProvider2) GetContentProviderIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ContentProviderId, true
}

// SetContentProviderId sets field value
func (o *ContentProvider2) SetContentProviderId(v int32) {
	o.ContentProviderId = v
}

// GetName returns the Name field value
func (o *ContentProvider2) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ContentProvider2) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ContentProvider2) SetName(v string) {
	o.Name = v
}

func (o ContentProvider2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["contentProviderId"] = o.ContentProviderId
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableContentProvider2 struct {
	value *ContentProvider2
	isSet bool
}

func (v NullableContentProvider2) Get() *ContentProvider2 {
	return v.value
}

func (v *NullableContentProvider2) Set(val *ContentProvider2) {
	v.value = val
	v.isSet = true
}

func (v NullableContentProvider2) IsSet() bool {
	return v.isSet
}

func (v *NullableContentProvider2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentProvider2(val *ContentProvider2) *NullableContentProvider2 {
	return &NullableContentProvider2{value: val, isSet: true}
}

func (v NullableContentProvider2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentProvider2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


