/*
content-delivery

Cotent Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// LimitRate Limit bandwidth per session, in bytes per second.
type LimitRate struct {
	// The name of the behavior, `limitRate` in this case.
	Name string `json:"name"`
	Options LimitRateOptions `json:"options"`
}

// NewLimitRate instantiates a new LimitRate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLimitRate(name string, options LimitRateOptions) *LimitRate {
	this := LimitRate{}
	this.Name = name
	this.Options = options
	return &this
}

// NewLimitRateWithDefaults instantiates a new LimitRate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLimitRateWithDefaults() *LimitRate {
	this := LimitRate{}
	return &this
}

// GetName returns the Name field value
func (o *LimitRate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LimitRate) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LimitRate) SetName(v string) {
	o.Name = v
}

// GetOptions returns the Options field value
func (o *LimitRate) GetOptions() LimitRateOptions {
	if o == nil {
		var ret LimitRateOptions
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *LimitRate) GetOptionsOk() (*LimitRateOptions, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Options, true
}

// SetOptions sets field value
func (o *LimitRate) SetOptions(v LimitRateOptions) {
	o.Options = v
}

func (o LimitRate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["options"] = o.Options
	}
	return json.Marshal(toSerialize)
}

type NullableLimitRate struct {
	value *LimitRate
	isSet bool
}

func (v NullableLimitRate) Get() *LimitRate {
	return v.value
}

func (v *NullableLimitRate) Set(val *LimitRate) {
	v.value = val
	v.isSet = true
}

func (v NullableLimitRate) IsSet() bool {
	return v.isSet
}

func (v *NullableLimitRate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLimitRate(val *LimitRate) *NullableLimitRate {
	return &NullableLimitRate{value: val, isSet: true}
}

func (v NullableLimitRate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLimitRate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


