/*
content-delivery

Aura LCDN Content Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// X509CertificateSummaryTypeIssuedBy A distinguished name (DN) that identifies the certificate authorizer.
type X509CertificateSummaryTypeIssuedBy struct {
	// The organization of the certificate authorizer.
	Organization string `json:"organization"`
	// The entity (user/web server/domain/hostname) associated with the certificate authorizer.
	CommonName string `json:"commonName"`
	// The organizational unit of the certificate issuer.
	OrganizationalUnit string `json:"organizationalUnit"`
}

// NewX509CertificateSummaryTypeIssuedBy instantiates a new X509CertificateSummaryTypeIssuedBy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewX509CertificateSummaryTypeIssuedBy(organization string, commonName string, organizationalUnit string) *X509CertificateSummaryTypeIssuedBy {
	this := X509CertificateSummaryTypeIssuedBy{}
	this.Organization = organization
	this.CommonName = commonName
	this.OrganizationalUnit = organizationalUnit
	return &this
}

// NewX509CertificateSummaryTypeIssuedByWithDefaults instantiates a new X509CertificateSummaryTypeIssuedBy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewX509CertificateSummaryTypeIssuedByWithDefaults() *X509CertificateSummaryTypeIssuedBy {
	this := X509CertificateSummaryTypeIssuedBy{}
	return &this
}

// GetOrganization returns the Organization field value
func (o *X509CertificateSummaryTypeIssuedBy) GetOrganization() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value
// and a boolean to check if the value has been set.
func (o *X509CertificateSummaryTypeIssuedBy) GetOrganizationOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Organization, true
}

// SetOrganization sets field value
func (o *X509CertificateSummaryTypeIssuedBy) SetOrganization(v string) {
	o.Organization = v
}

// GetCommonName returns the CommonName field value
func (o *X509CertificateSummaryTypeIssuedBy) GetCommonName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CommonName
}

// GetCommonNameOk returns a tuple with the CommonName field value
// and a boolean to check if the value has been set.
func (o *X509CertificateSummaryTypeIssuedBy) GetCommonNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CommonName, true
}

// SetCommonName sets field value
func (o *X509CertificateSummaryTypeIssuedBy) SetCommonName(v string) {
	o.CommonName = v
}

// GetOrganizationalUnit returns the OrganizationalUnit field value
func (o *X509CertificateSummaryTypeIssuedBy) GetOrganizationalUnit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationalUnit
}

// GetOrganizationalUnitOk returns a tuple with the OrganizationalUnit field value
// and a boolean to check if the value has been set.
func (o *X509CertificateSummaryTypeIssuedBy) GetOrganizationalUnitOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.OrganizationalUnit, true
}

// SetOrganizationalUnit sets field value
func (o *X509CertificateSummaryTypeIssuedBy) SetOrganizationalUnit(v string) {
	o.OrganizationalUnit = v
}

func (o X509CertificateSummaryTypeIssuedBy) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["organization"] = o.Organization
	}
	if true {
		toSerialize["commonName"] = o.CommonName
	}
	if true {
		toSerialize["organizationalUnit"] = o.OrganizationalUnit
	}
	return json.Marshal(toSerialize)
}

type NullableX509CertificateSummaryTypeIssuedBy struct {
	value *X509CertificateSummaryTypeIssuedBy
	isSet bool
}

func (v NullableX509CertificateSummaryTypeIssuedBy) Get() *X509CertificateSummaryTypeIssuedBy {
	return v.value
}

func (v *NullableX509CertificateSummaryTypeIssuedBy) Set(val *X509CertificateSummaryTypeIssuedBy) {
	v.value = val
	v.isSet = true
}

func (v NullableX509CertificateSummaryTypeIssuedBy) IsSet() bool {
	return v.isSet
}

func (v *NullableX509CertificateSummaryTypeIssuedBy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableX509CertificateSummaryTypeIssuedBy(val *X509CertificateSummaryTypeIssuedBy) *NullableX509CertificateSummaryTypeIssuedBy {
	return &NullableX509CertificateSummaryTypeIssuedBy{value: val, isSet: true}
}

func (v NullableX509CertificateSummaryTypeIssuedBy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableX509CertificateSummaryTypeIssuedBy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


