/*
content-delivery

Cotent Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// HttpDeliveryOptions This behavior's set of configuration options.
type HttpDeliveryOptions struct {
	Value DeliveryOverrideType `json:"value"`
}

// NewHttpDeliveryOptions instantiates a new HttpDeliveryOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHttpDeliveryOptions(value DeliveryOverrideType) *HttpDeliveryOptions {
	this := HttpDeliveryOptions{}
	this.Value = value
	return &this
}

// NewHttpDeliveryOptionsWithDefaults instantiates a new HttpDeliveryOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHttpDeliveryOptionsWithDefaults() *HttpDeliveryOptions {
	this := HttpDeliveryOptions{}
	var value DeliveryOverrideType = DELIVERYOVERRIDETYPE_DEFAULT
	this.Value = value
	return &this
}

// GetValue returns the Value field value
func (o *HttpDeliveryOptions) GetValue() DeliveryOverrideType {
	if o == nil {
		var ret DeliveryOverrideType
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *HttpDeliveryOptions) GetValueOk() (*DeliveryOverrideType, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *HttpDeliveryOptions) SetValue(v DeliveryOverrideType) {
	o.Value = v
}

func (o HttpDeliveryOptions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableHttpDeliveryOptions struct {
	value *HttpDeliveryOptions
	isSet bool
}

func (v NullableHttpDeliveryOptions) Get() *HttpDeliveryOptions {
	return v.value
}

func (v *NullableHttpDeliveryOptions) Set(val *HttpDeliveryOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableHttpDeliveryOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableHttpDeliveryOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHttpDeliveryOptions(val *HttpDeliveryOptions) *NullableHttpDeliveryOptions {
	return &NullableHttpDeliveryOptions{value: val, isSet: true}
}

func (v NullableHttpDeliveryOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHttpDeliveryOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


