/*
content-delivery

Aura LCDN Content Delivery API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package content_delivery

import (
	"encoding/json"
)

// UriSignature The URI signature pattern provides a mechanism to express URI signing parameters and mechanisms to be enforced across an entire CDN prefix, or for a narrower subset of a CDN prefix identified by a particular URI pattern.
type UriSignature struct {
	// The name of the behavior, `uriSignature` in this case.
	Name string `json:"name"`
	Options UriSignatureOptions `json:"options"`
}

// NewUriSignature instantiates a new UriSignature object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUriSignature(name string, options UriSignatureOptions) *UriSignature {
	this := UriSignature{}
	this.Name = name
	this.Options = options
	return &this
}

// NewUriSignatureWithDefaults instantiates a new UriSignature object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUriSignatureWithDefaults() *UriSignature {
	this := UriSignature{}
	return &this
}

// GetName returns the Name field value
func (o *UriSignature) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UriSignature) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UriSignature) SetName(v string) {
	o.Name = v
}

// GetOptions returns the Options field value
func (o *UriSignature) GetOptions() UriSignatureOptions {
	if o == nil {
		var ret UriSignatureOptions
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *UriSignature) GetOptionsOk() (*UriSignatureOptions, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Options, true
}

// SetOptions sets field value
func (o *UriSignature) SetOptions(v UriSignatureOptions) {
	o.Options = v
}

func (o UriSignature) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["options"] = o.Options
	}
	return json.Marshal(toSerialize)
}

type NullableUriSignature struct {
	value *UriSignature
	isSet bool
}

func (v NullableUriSignature) Get() *UriSignature {
	return v.value
}

func (v *NullableUriSignature) Set(val *UriSignature) {
	v.value = val
	v.isSet = true
}

func (v NullableUriSignature) IsSet() bool {
	return v.isSet
}

func (v *NullableUriSignature) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUriSignature(val *UriSignature) *NullableUriSignature {
	return &NullableUriSignature{value: val, isSet: true}
}

func (v NullableUriSignature) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUriSignature) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


